"""empty message

Revision ID: 152486e816d7
Revises: 
Create Date: 2024-03-19 10:25:19.032192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152486e816d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('product')
    # with op.batch_alter_table('customer', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['ProductId'], ['ProductId'])

    # op.create_table('product',
    # sa.Column('ProductId', sa.INTEGER(), nullable=False),
    # sa.Column('Name', sa.VARCHAR(length=128), nullable=True),
    # sa.Column('Description', sa.VARCHAR(length=2000), nullable=True),
    # sa.Column('Price', sa.FLOAT(), nullable=True),
    # sa.Column('DateCreated', sa.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('ProductId')
    # )
    # ### end Alembic commands ###
