"""Initial Migration

Revision ID: 918e531e9887
Revises: 
Create Date: 2024-02-28 15:02:02.443934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918e531e9887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Default', sa.Boolean(), nullable=True),
    sa.Column('Permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('RoleId')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_Default'), ['Default'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('ContactName',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('ContactEmail',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('Note',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('Password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('Role',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Role',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('Password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('Email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('Name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('Note',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('ContactEmail',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('ContactName',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('Description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('Name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_Default'))

    op.drop_table('role')
    # ### end Alembic commands ###
